### PR TITLE
Add CancelledRecurringDonationsReport

### PR DESCRIPTION
**Pull request by wwahammy**
- Add way to query for recurring donations cancelled before a particular time
- Add PeriodicReportAdapter::CancelledRecurringDonationsReport

### CODE REVIEW

**Review by clarissalimab — APPROVED** [review]
Nice job! :sparkles:

**Review by clarissalimab — APPROVED** [review]
I approved this one already!

**Comment by wwahammy** [comment]
@clarissalimab I made some slight changes but thanks for the approval :smile:

**Comment by clarissalimab** [comment]
Oh, I couldn't see what the new changes were, github didn't show me that "new changes" thing.

**Pull request merged**
