### PR TITLE
Makes anonymous supporter field false by default

### PR DESCRIPTION
**Pull request by clarissalimab**
Part of [tix #3258](https://github.com/CommitChange/tix/issues/3258).

### CODE REVIEW

**Review by wwahammy — APPROVED** [review]
Perfect!

**Comment by wwahammy** [comment]
Nice job @clarissalimab! Please merge and deploy

**Comment by wwahammy** [comment]
@clarissalimab also, did you run specs? :)

**Comment by clarissalimab** [comment]
I ran the tests!

**Pull request merged**
