### PR TITLE
Makes anonymous field from supporters not nullable

### PR DESCRIPTION
**Pull request by clarissalimab**
Closes [tix #3258](https://github.com/CommitChange/tix/issues/3258).

By the way, I learned that I could have used `change_column_null :supporters, :anonymous, false, false`, using the last argument to fix existing data instead of the script > [Reference](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-change_column_null).

### CODE REVIEW

**Comment by wwahammy** [comment]
> By the way, I learned that I could have used `change_column_null :supporters, :anonymous, false, false`, using the last argument to fix existing data instead of the script > [Reference](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/SchemaStatements.html#method-i-change_column_null).

:exploding_head: That's amazing! Definitely do that going forward!

**Comment by wwahammy** [comment]
ACTUALLY: maybe not do that. The problem with that is that it locks the entire table. Check and see how long it takes to run locally before you do that.

**Review by wwahammy — APPROVED** [review]
Check to see how long the version of `change_column_null` runs where you change all of the nulls to false. If that's pretty fast locally (under a second?), I support using that instead but otherwise, this is fine.

**Comment by clarissalimab** [comment]
It was pretty fast with recurring donations, but it has less records. I'm going to restore the old database to see.

**Comment by clarissalimab** [comment]
It took to long (`25.7012s`), I think we should keep doing as we did.

**Comment by clarissalimab** [comment]
I'm going to merge this one!

**Pull request merged**
