### PR TITLE
Mailchimp Merge Tags

### PR DESCRIPTION
**Pull request by wwahammy**
Closes https://github.com/CommitChange/tix/issues/3758

Depends on #310 
Depends on #333
Depends on #340
Depends on #347
Depends on #348

- WIP
- WIP
- Add list.json.jbuilder
- Mailchimp passes for creating with merge_tags

### CODE REVIEW

**Comment by wwahammy** [comment]
@clarissalimab I need to clean up the commit history but this is otherwise ready for review and I think merging.

**Comment by clarissalimab** [comment]
Is this PR doing what's described on https://github.com/CommitChange/tix/issues/3758?

**Comment by wwahammy** [comment]
@clarissalimab Oops, yes. I'll add the closes to it.

**Review by clarissalimab — APPROVED** [review]
It looks good to me!

**Pull request merged**
