### PR TITLE
Add an email method to MailchimpBatchOperation

### PR DESCRIPTION
**Pull request by wwahammy**
**NOTE: DO NOT discuss internal CommitChange information in your PR; this PR will be public.
Link back to the issue in the Tix repo when you need to do that.**

Closes https://github.com/CommitChange/tix/issues/4102

### CODE REVIEW

**Comment by wwahammy** [comment]
This isn't totally necessary now but it's good design so let's add it

**Comment by wwahammy** [comment]
Oops, didn't mean to close.

**Comment by camckin10** [comment]
@wwahammy  What makes this a good design for later?

**Comment by wwahammy** [comment]
> @wwahammy What makes this a good design for later?

The general thinking I have is that we could abstract MailchimpBatchOperation to be useful in cases where the subscriber doesn't correspond to a `Supporter`. If we move email into its own method, we can have multiple classes which get the email from a different places. For example, let's say we want to subscribe or unsubscribe a `User` from a list. We could create have a class which inherits from the abstracted MailchimpBatchOperation which can reuse `path` and `to_h` methods since they don't expect there to be a `supporter` field like they did previously.

**Comment by camckin10** [comment]
> > @wwahammy What makes this a good design for later?
> 
> The general thinking I have is that we could abstract MailchimpBatchOperation to be useful in cases where the subscriber doesn't correspond to a `Supporter`. If we move email into its own method, we can have multiple classes which get the email from a different places. For example, let's say we want to subscribe or unsubscribe a `User` from a list. We could create have a class which inherits from the abstracted MailchimpBatchOperation which can reuse `path` and `to_h` methods since they don't expect there to be a `supporter` field like they did previously.

WOW! That sounds interesting. Thank you for explaining.

**Review by camckin10 — APPROVED** [review]
lgtm. Thanks for the explanation.

**Pull request merged**
